services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: cerv1no
      POSTGRES_PASSWORD: cerv1no
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  configserverms:
    image: cerv1no/configserverms:latest
    container_name: configserverms
    ports:
      - 8080:8080
    networks:
      - ms-network
    depends_on:
      - servicereg
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  servicereg:
    image: cerv1no/servicereg:latest
    container_name: servicereg
    ports:
      - "8761:8761"
    networks:
      - ms-network
      - postgres
    depends_on:
      - postgres
      - rabbitmq
      - zipkin
      - pgadmin

  companyms:
    image: cerv1no/companyms:latest
    container_name: company
    ports:
      - "8081:8081"
    networks:
      - ms-network
      - postgres
    depends_on:
      - servicereg
      - configserverms
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  jobms:
    image: cerv1no/jobms:latest
    container_name: job
    ports:
      - "8082:8082"
    networks:
      - ms-network
      - postgres
    depends_on:
      - servicereg
      - configserverms
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka/

  reviewms:
    image: cerv1no/reviewms:latest
    container_name: review
    ports:
      - "8083:8083"
    networks:
      - ms-network
      - postgres
    depends_on:
      - servicereg
      - configserverms
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - postgres
      - ms-network

  gatewayms:
    image: cerv1no/gatewayms:latest
    container_name: gateway
    ports:
      - "8084:8084"
    networks:
      - ms-network
      - postgres
    depends_on:
      - servicereg
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  postgres:
    driver: bridge
  ms-network:
    driver: bridge

volumes:
  postgres:
  pgadmin: